### ISSUE TITLE
Email date range

### ISSUE THREAD

**Issue by emurnane** [emurnane/EmailDrivenAppsEngine#26]
What is the date range of emails included in gameplay? (Emails from start date X through end date Y?)

Please respond in the Comments, and feel free to link to any relevant source code.

**Comment by ik226** [comment]
it is intended to have a range of **29** days of emails.
in imap/imap.js there is a GLOBALS object that has a property called daysOfEmail. 
Then, at line 85, it intends to make a Date object with a date that is 29 days ago 

``` javascript
var dateXDaysBack = new Date().subtractDays(GLOBALS.daysOfEmail).toDateString();
  imap.search([ 'ALL', ['SINCE', dateXDaysBack] ], function(err, results) {
      ...
  }
```

But I guess that should not work properly since there is no `subtractDays()` methods
in Date object.... it should be in such form:

``` javascript
var dateXDaysBack = new Date();
dateXdaysBack.setDate(dateXDaysBack.getDate()-GLOBALS.daysOfEmail);
```

I will make pull request on this

**Comment by emurnane** [comment]
Okay thanks! It would be nice for users to get a choice about what date range they play as a future feature — adding a (currently low priority) issue:  https://github.com/emurnane/EmailDrivenAppsEngine/issues/29
